# Copyright 2025 The MCP Interceptors Authors. All rights reserved.
# Use of this source code is governed by an Apache-2.0
# license that can be found in the LICENSE file.

"""The Python view of the language-neutral conformance fixture format
(`conformance/schema/fixture.schema.json`).

The JSON files under ``conformance/fixtures/`` are the shared artifact this
adapter consumes UNCHANGED — they are generated by the TypeScript catalog
(`conformance/src/catalog.ts`) and are the oracle; nothing here re-derives an
expectation. Parsing is strict: emitted fixtures always carry the
generator-computed ``canonical`` / ``finalPayloadCanonical`` strings (the
suite's meta-tests pin that), so their absence is a malformed-artifact error,
not a case to tolerate.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

# ── vocabularies (mirrors fixture-types.ts) ──────────────────────────────────

Phase = Literal["request", "response"]
HookPhases = Literal["request", "response", "both"]
Mode = Literal["enforce", "audit"]
Decision = Literal["allow", "deny"]
StepOp = Literal["list", "invoke", "chain"]

BEHAVIORS: frozenset[str] = frozenset(
    {
        "allow-all",
        "deny-all",
        "require-note",
        "require-uppercase-note",
        "uppercase-note",
        "crash",
        "cross-boundary-guard",
        "secretless-redactor",
    }
)

# ── fixture setup ────────────────────────────────────────────────────────────


@dataclass(frozen=True, kw_only=True)
class FixtureInterceptor:
    """Declarative interceptor the adapter must register before replaying steps."""

    name: str
    type: Literal["validation", "mutation"]
    behavior: str
    events: tuple[str, ...]
    phases: HookPhases
    #: Absent on the wire when the default (``enforce``).
    mode: Mode | None
    #: Absent on the wire when the default (``False``).
    fail_open: bool | None


# ── step expectations ────────────────────────────────────────────────────────


@dataclass(frozen=True, kw_only=True)
class ResultExpectation:
    """Exact-bytes expectation: actual must JCS-canonicalize to ``canonical``."""

    result: Any
    canonical: str


@dataclass(frozen=True, kw_only=True)
class ErrorExpectation:
    """JSON-RPC error expectation (e.g. invoking an unknown interceptor name)."""

    error_code: int


@dataclass(frozen=True, kw_only=True)
class DecisionExpectation:
    decision: Decision
    #: Generator-computed JCS form of the expected final payload; None when the
    #: fixture does not pin exact payload bytes.
    final_payload_canonical: str | None
    #: Substrings that MUST NOT appear in the canonicalized final payload.
    forbids: tuple[str, ...]
    #: Substrings that MUST appear in the canonicalized final payload.
    requires: tuple[str, ...]


# ── steps ────────────────────────────────────────────────────────────────────


@dataclass(frozen=True, kw_only=True)
class ListStep:
    op: Literal["list"]
    event: str | None
    expect: ResultExpectation


@dataclass(frozen=True, kw_only=True)
class InvokeParams:
    name: str
    event: str
    phase: Phase
    payload: Any


@dataclass(frozen=True, kw_only=True)
class InvokeStep:
    op: Literal["invoke"]
    params: InvokeParams
    expect: ResultExpectation | ErrorExpectation


@dataclass(frozen=True, kw_only=True)
class ChainStep:
    op: Literal["chain"]
    event: str
    phase: Phase
    payload: Any
    #: Session correlation for stateful (security) interceptors; None = stateless.
    session_id: str | None
    expect: DecisionExpectation


FixtureStep = ListStep | InvokeStep | ChainStep


@dataclass(frozen=True, kw_only=True)
class Fixture:
    id: str
    kind: Literal["protocol", "behavior"]
    requirement: str
    description: str
    interceptors: tuple[FixtureInterceptor, ...]
    steps: tuple[FixtureStep, ...]
    volatile: tuple[str, ...]


# ── parsing (the artifact boundary; strict) ──────────────────────────────────


def _parse_interceptor(raw: dict[str, Any]) -> FixtureInterceptor:
    behavior = raw["behavior"]
    if behavior not in BEHAVIORS:
        raise ValueError(f"unknown fixture behavior {behavior!r}")
    return FixtureInterceptor(
        name=raw["name"],
        type=raw["type"],
        behavior=behavior,
        events=tuple(raw["events"]),
        phases=raw["phases"],
        mode=raw.get("mode"),
        fail_open=raw.get("failOpen"),
    )


def _parse_result_expectation(raw: dict[str, Any], where: str) -> ResultExpectation:
    if "canonical" not in raw:
        raise ValueError(f"{where}: emitted fixtures always carry a generator-computed 'canonical'")
    return ResultExpectation(result=raw["result"], canonical=raw["canonical"])


def _parse_list_step(raw: dict[str, Any], where: str) -> ListStep:
    return ListStep(op="list", event=raw["event"], expect=_parse_result_expectation(raw["expect"], where))


def _parse_invoke_step(raw: dict[str, Any], where: str) -> InvokeStep:
    raw_expect = raw["expect"]
    expect: ResultExpectation | ErrorExpectation
    if "errorCode" in raw_expect:
        expect = ErrorExpectation(error_code=raw_expect["errorCode"])
    else:
        expect = _parse_result_expectation(raw_expect, where)
    p = raw["params"]
    return InvokeStep(
        op="invoke",
        params=InvokeParams(name=p["name"], event=p["event"], phase=p["phase"], payload=p["payload"]),
        expect=expect,
    )


def _parse_chain_step(raw: dict[str, Any], where: str) -> ChainStep:
    raw_expect = raw["expect"]
    if "finalPayload" in raw_expect and "finalPayloadCanonical" not in raw_expect:
        raise ValueError(f"{where}: finalPayload without generator-computed finalPayloadCanonical")
    context = raw["context"]
    return ChainStep(
        op="chain",
        event=raw["event"],
        phase=raw["phase"],
        payload=raw["payload"],
        session_id=None if context is None else context["sessionId"],
        expect=DecisionExpectation(
            decision=raw_expect["decision"],
            final_payload_canonical=raw_expect.get("finalPayloadCanonical"),
            forbids=tuple(raw_expect.get("forbids", ())),
            requires=tuple(raw_expect.get("requires", ())),
        ),
    )


_PARSE_STEP = {
    "list": _parse_list_step,
    "invoke": _parse_invoke_step,
    "chain": _parse_chain_step,
}


def parse_fixture(raw: dict[str, Any]) -> Fixture:
    fixture_id = raw["id"]
    return Fixture(
        id=fixture_id,
        kind=raw["kind"],
        requirement=raw["requirement"],
        description=raw["description"],
        interceptors=tuple(_parse_interceptor(i) for i in raw["interceptors"]),
        steps=tuple(
            _PARSE_STEP[step["op"]](step, f"{fixture_id} step {index}")
            for index, step in enumerate(raw["steps"])
        ),
        volatile=tuple(raw["volatile"]),
    )


def load_fixture(path: Path) -> Fixture:
    return parse_fixture(json.loads(path.read_text(encoding="utf-8")))


def load_suite(conformance_root: Path) -> tuple[Fixture, ...]:
    """Load every fixture named by the shared traceability manifest, in
    manifest order (the same order the TypeScript catalog declares)."""
    manifest = json.loads((conformance_root / "manifest.json").read_text(encoding="utf-8"))
    return tuple(load_fixture(conformance_root / entry["file"]) for entry in manifest["fixtures"])
