# Copyright 2025 The MCP Interceptors Authors. All rights reserved.
# Use of this source code is governed by an Apache-2.0
# license that can be found in the LICENSE file.

"""
MCP Interceptors Python SDK

Implements MCP Interceptors based on SEP-2624:
https://github.com/modelcontextprotocol/modelcontextprotocol/pull/2624
"""

from mcp_ext_interceptors.chain import (
    AbortInfo,
    Chain,
    ChainEntry,
    ChainExecutionParams,
    ChainExecutionResult,
    ChainStatus,
    Direction,
    ExecutionHandler,
    InterceptorOverrides,
    ValidationSummary,
)
from mcp_ext_interceptors.client import (
    InvokerTarget,
    invoke_interceptor,
    list_interceptors,
    read_interceptors_capability,
)
from mcp_ext_interceptors.interceptor import (
    Invocation,
    Mutator,
    MutatorHandler,
    RegisteredInterceptor,
    Validator,
    ValidatorHandler,
)
from mcp_ext_interceptors.server import Interceptors
from mcp_ext_interceptors.types import (
    EVENT_ELICITATION_CREATE,
    EVENT_LLM_COMPLETION,
    EVENT_PROMPTS_GET,
    EVENT_PROMPTS_LIST,
    EVENT_RESOURCES_LIST,
    EVENT_RESOURCES_READ,
    EVENT_RESOURCES_SUBSCRIBE,
    EVENT_ROOTS_LIST,
    EVENT_SAMPLING_CREATE_MESSAGE,
    EVENT_TOOLS_CALL,
    EVENT_TOOLS_LIST,
    EVENT_WILDCARD,
    EXTENSION_ID,
    INTERCEPTOR_MUTATION_FAILED,
    INTERCEPTOR_TIMEOUT,
    INTERCEPTOR_VALIDATION_FAILED,
    METHOD_INVOKE,
    METHOD_LIST,
    TYPE_MUTATION,
    TYPE_VALIDATION,
    AnyInvokeResult,
    Compat,
    Hook,
    InterceptorInfo,
    InterceptorsCapability,
    InvocationContext,
    InvokeInterceptorParams,
    ListInterceptorsParams,
    ListInterceptorsResult,
    Mode,
    MutationResult,
    Phase,
    PhasePriority,
    Principal,
    PriorityHint,
    Severity,
    UnknownInterceptorResult,
    ValidationMessage,
    ValidationResult,
    ValidationSuggestion,
    is_hook_subset,
    matches_hooks,
    parse_invoke_result,
    resolve_priority,
)

__all__ = [
    "EVENT_ELICITATION_CREATE",
    "EVENT_LLM_COMPLETION",
    "EVENT_PROMPTS_GET",
    "EVENT_PROMPTS_LIST",
    "EVENT_RESOURCES_LIST",
    "EVENT_RESOURCES_READ",
    "EVENT_RESOURCES_SUBSCRIBE",
    "EVENT_ROOTS_LIST",
    "EVENT_SAMPLING_CREATE_MESSAGE",
    "EVENT_TOOLS_CALL",
    "EVENT_TOOLS_LIST",
    "EVENT_WILDCARD",
    "EXTENSION_ID",
    "INTERCEPTOR_MUTATION_FAILED",
    "INTERCEPTOR_TIMEOUT",
    "INTERCEPTOR_VALIDATION_FAILED",
    "METHOD_INVOKE",
    "METHOD_LIST",
    "TYPE_MUTATION",
    "TYPE_VALIDATION",
    "AbortInfo",
    "AnyInvokeResult",
    "Chain",
    "ChainEntry",
    "ChainExecutionParams",
    "ChainExecutionResult",
    "ChainStatus",
    "Compat",
    "Direction",
    "ExecutionHandler",
    "Hook",
    "InterceptorInfo",
    "InterceptorOverrides",
    "Interceptors",
    "InterceptorsCapability",
    "Invocation",
    "InvocationContext",
    "InvokeInterceptorParams",
    "InvokerTarget",
    "ListInterceptorsParams",
    "ListInterceptorsResult",
    "Mode",
    "MutationResult",
    "Mutator",
    "MutatorHandler",
    "Phase",
    "PhasePriority",
    "Principal",
    "PriorityHint",
    "RegisteredInterceptor",
    "Severity",
    "UnknownInterceptorResult",
    "ValidationMessage",
    "ValidationResult",
    "ValidationSuggestion",
    "ValidationSummary",
    "Validator",
    "ValidatorHandler",
    "invoke_interceptor",
    "is_hook_subset",
    "list_interceptors",
    "matches_hooks",
    "parse_invoke_result",
    "read_interceptors_capability",
    "resolve_priority",
]
